### ISSUE TITLE
storage key in source

### ISSUE THREAD

**Issue by withinboredom** [MicrosoftDX/Dash#1]
Just wanted to let you know, you have storage keys committed in the code: https://github.com/MicrosoftDX/Dash/blob/master/DashServer.Azure/ServiceConfiguration.Cloud%20-%20East.cscfg

**Comment by jamesbak** [comment]
Thanks for the notification. 

The tests & configuration artifacts have now been refactored (as of commit: a4a6dfe) so that no secrets are kept in the source repo.

**Comment by withinboredom** [comment]
Welcome! 

I realized how difficult it was to keep them out of SCM so I started googling common parts of connection strings and letting people know it was committed.
