### ISSUE TITLE
Source file 'Properties\AssemblyVersion.cs' could not be found

### ISSUE THREAD

**Issue by thomasjungblut** [MicrosoftDX/Dash#2]
Hey guys,

I tried to compile from a fresh MASTER pull and it is missing the AssemblyVersion.cs file in the projects:

DashCommon
DashAsync
DashServer

Full error:
4>CSC : error CS2001: Source file 'Properties\AssemblyVersion.cs' could not be found

**Comment by jamesbak** [comment]
The AssemblyVersion.cs file is generated during the build by the CreateAssemblyInfoFromGit Nuget component. Try doing a nuget -restore and then build again.

**Comment by thomasjungblut** [comment]
stupid me, thank you. closing.
